
services:
  app:
    restart: always
    build: .
    ports:
      - "8080:8088"
    depends_on:
      - main_db
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main_db:5432/main_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    volumes:
      - type: volume
        source: image_storage
        target: /opt/app/image-storage

  main_db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=main_db
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"

networks:
  my-net:
    driver: bridge

volumes:
  image_storage:
  pg_data:
